29901.8 <c-58#150> Created logger
29902 <c-58#150> appl_initialize was called
29902 <c-58#150:24> Logger was updated
29902 <c-58#150:24> Started intializing cube lib
29902 <c-58#150:24> Finished intializing cube lib with worker, starting to work
29905 <c-58#150:24> requestCubes => [52] Buffer size: 0
29905 <c-58#150:24> Sent requestCubes signal to root
29905 <c-58#150:24> Received 64 cubes from root
29905 <c-58#150:24> The main loop continues
29905 <c-58#150:24> Started solving a cube
29905 <c-58#150:24> Cube failed
29905 <c-58#150:24> Added failed cube
29905 <c-58#150:24> Started solving a cube
29905 <c-58#150:24> Cube failed
29905 <c-58#150:24> Added failed cube
29905 <c-58#150:24> Started solving a cube
29936.1 <c-58#150:24> appl_pause was called
29936.1 <c-58#150:24> Set suspended
29936.1 <c-58#150:24> Suspending worker
29936.2 <c-58#150:24> SUSPEND (0.28s since last cb)
30113.2 <c-58#150:24> appl_interrupt was called
30113.2 <c-58#150:24> Interrupting worker
30113.2 <c-58#150:24> Resuming worker to allow interruption
30113.2 <c-58#150:24> RESUME
30113.2 <c-58#150:24> STOP after suspension
30113.2 <c-58#150:24> appl_interrupt was called
30113.2 <c-58#150:24> appl_withdraw was called
30113.2 <c-58#150:24> Started withdraw thread
30113.7 <c-58#150:24> Solving interrupted
30113.7 <c-58#150:24> The main loop continues
30113.7 <c-58#150:24> Leaving the main loop due to an interruption
30113.7 <c-58#150:24> Finished withdrawing lib
30113.7 <c-58#150:24> Enter destructor of CubeWorker
30113.7 <c-58#150:24> Time waiting for messages: 0.000
30113.9 <c-58#150:24> Enter destructor of CubeWorkerInterface
30113.9 <c-58#150:24> Enter destructor of CubeRoot
30113.9 <c-58#150:24> Finished withdraw thread
30174.5 <c-58#150:24> Enter destructor
30174.5 <c-58#150:24> Time working: 34.145
30174.5 <c-58#150:24> Time suspended: 177.051
30174.5 <c-58#150:24> Joined cleanup thread
30174.5 <c-58#150:24> Exit destructor
30174.5 <c-58#150:24> Destructing logger
