25515.1 <c-16#138> Created logger
25515.1 <c-16#138:20> Logger was updated
25515.1 <c-16#138:20> Started intializing cube lib
25515.1 <c-16#138:20> Finished intializing cube lib with worker
25515.2 <c-16#138:20> requestCubes => [58] Buffer size: 0
25515.2 <c-16#138:20> Sent requestCubes signal to root
25515.2 <c-16#138:20> Received 4 cubes from root
25515.2 <c-16#138:20> The main loop continues
25515.2 <c-16#138:20> Started solving a cube
25532.7 <c-16#138:20> Cube failed
25532.7 <c-16#138:20> Added failed cube
25532.7 <c-16#138:20> Started solving a cube
25556.7 <c-16#138:20> Cube failed
25556.7 <c-16#138:20> Added failed cube
25556.7 <c-16#138:20> Started solving a cube
25771.5 <c-16#138:20> Cube failed
25771.5 <c-16#138:20> Added failed cube
25771.5 <c-16#138:20> Started solving a cube
26010.7 <c-16#138:20> appl_pause was called
26010.8 <c-16#138:20> SUSPEND (0.05s since last cb)
26122 <c-16#138:20> appl_unpause was called
26122 <c-16#138:20> RESUME
26144.3 <c-16#138:20> appl_pause was called
26144.3 <c-16#138:20> SUSPEND (0.06s since last cb)
26460 <c-16#138:20> appl_interrupt was called
26460.1 <c-16#138:20> RESUME
26460.1 <c-16#138:20> STOP after suspension
26460.1 <c-16#138:20> Solving interrupted
26460.1 <c-16#138:20> The main loop continues
26460.1 <c-16#138:20> appl_interrupt was called
26460.1 <c-16#138:20> appl_withdraw was called
26460.1 <c-16#138:20> Leaving the main loop due to an interruption
26460.1 <c-16#138:20> Started withdraw thread
26460.1 <c-16#138:20> Enter destructor of CubeWorker
26460.1 <c-16#138:20> Time waiting for messages: 0.000
26460.1 <c-16#138:20> Enter destructor of CubeWorkerInterface
26460.1 <c-16#138:20> Enter destructor of CubeRoot
26460.1 <c-16#138:20> Finished withdraw thread
26521.9 <c-16#138:20> Enter destructor
26521.9 <c-16#138:20> Time working: 22.346
26521.9 <c-16#138:20> Time suspended: 315.723
26521.9 <c-16#138:20> Joined cleanup thread
26521.9 <c-16#138:20> Exit destructor
26521.9 <c-16#138:20> Destructing logger
