10653.9 <c-29#67> Created logger
10653.9 <c-29#67> appl_initialize was called
10653.9 <c-29#67:2> Logger was updated
10653.9 <c-29#67:2> Started intializing cube lib
10653.9 <c-29#67:2> Finished intializing cube lib with worker, starting to work
10654 <c-29#67:2> requestCubes => [56] Buffer size: 0
10654 <c-29#67:2> Sent requestCubes signal to root
10654 <c-29#67:2> Received 1 cubes from root
10654 <c-29#67:2> The main loop continues
10654 <c-29#67:2> Started solving a cube
10654 <c-29#67:2> Cube failed
10654 <c-29#67:2> Added failed cube
10654 <c-29#67:2> returnFailedCubes => [56] Buffer size: 4
10654 <c-29#67:2> Sent 1 failed cubes to root
10654 <c-29#67:2> Received receivedFailedCubes signal from root
10654 <c-29#67:2> requestCubes => [56] Buffer size: 0
10654 <c-29#67:2> Sent requestCubes signal to root
10654 <c-29#67:2> Received 1 cubes from root
10654 <c-29#67:2> The main loop continues
10654 <c-29#67:2> Started solving a cube
11636.9 <c-29#67:2> appl_interrupt was called
11636.9 <c-29#67:2> Interrupting worker
11636.9 <c-29#67:2> appl_interrupt was called
11636.9 <c-29#67:2> appl_withdraw was called
11636.9 <c-29#67:2> Started withdraw thread
11636.9 <c-29#67:2> STOP (0.00s since last cb)
11636.9 <c-29#67:2> Solving interrupted
11636.9 <c-29#67:2> The main loop continues
11636.9 <c-29#67:2> Leaving the main loop due to an interruption
11636.9 <c-29#67:2> Finished withdrawing lib
11636.9 <c-29#67:2> Enter destructor of CubeWorker
11636.9 <c-29#67:2> Time waiting for messages: 0.002
11637 <c-29#67:2> Enter destructor of CubeWorkerInterface
11637 <c-29#67:2> Enter destructor of CubeRoot
11637 <c-29#67:2> Finished withdraw thread
11699.6 <c-29#67:2> Enter destructor
11699.6 <c-29#67:2> Time working: 983.024
11699.6 <c-29#67:2> Time suspended: 0.000
11699.6 <c-29#67:2> Joined cleanup thread
11699.6 <c-29#67:2> Exit destructor
11699.6 <c-29#67:2> Destructing logger
