53441 <c-29#310> Created logger
53441 <c-29#310> appl_initialize was called
53441 <c-29#310:7> Logger was updated
53441 <c-29#310:7> Started intializing cube lib
53441 <c-29#310:7> Finished intializing cube lib with worker, starting to work
53441 <c-29#310:7> requestCubes => [17] Buffer size: 0
53441 <c-29#310:7> Sent requestCubes signal to root
53441 <c-29#310:7> Received 1 cubes from root
53441 <c-29#310:7> The main loop continues
53441 <c-29#310:7> Started solving a cube
53639.6 <c-29#310:7> Cube failed
53639.6 <c-29#310:7> Added failed cube
53639.6 <c-29#310:7> returnFailedCubes => [17] Buffer size: 5
53639.6 <c-29#310:7> Sent 1 failed cubes to root
53639.6 <c-29#310:7> Received receivedFailedCubes signal from root
53639.6 <c-29#310:7> requestCubes => [17] Buffer size: 0
53639.6 <c-29#310:7> Sent requestCubes signal to root
53639.6 <c-29#310:7> Received 1 cubes from root
53639.6 <c-29#310:7> The main loop continues
53639.6 <c-29#310:7> Started solving a cube
53653.9 <c-29#310:7> appl_interrupt was called
53653.9 <c-29#310:7> Interrupting worker
53653.9 <c-29#310:7> appl_interrupt was called
53653.9 <c-29#310:7> appl_withdraw was called
53653.9 <c-29#310:7> Started withdraw thread
53653.9 <c-29#310:7> STOP (0.00s since last cb)
53653.9 <c-29#310:7> Solving interrupted
53653.9 <c-29#310:7> The main loop continues
53653.9 <c-29#310:7> Leaving the main loop due to an interruption
53653.9 <c-29#310:7> Finished withdrawing lib
53653.9 <c-29#310:7> Enter destructor of CubeWorker
53653.9 <c-29#310:7> Time waiting for messages: 0.000
53653.9 <c-29#310:7> Enter destructor of CubeWorkerInterface
53653.9 <c-29#310:7> Enter destructor of CubeRoot
53653.9 <c-29#310:7> Finished withdraw thread
53715.7 <c-29#310:7> Enter destructor
53715.7 <c-29#310:7> Time working: 212.926
53715.7 <c-29#310:7> Time suspended: 0.000
53715.7 <c-29#310:7> Joined cleanup thread
53715.7 <c-29#310:7> Exit destructor
53715.7 <c-29#310:7> Destructing logger
