58300.7 <c-48#309> Created logger
58300.7 <c-48#309:17> Logger was updated
58300.7 <c-48#309:17> Started intializing cube lib
58300.7 <c-48#309:17> Finished intializing cube lib with worker
58300.8 <c-48#309:17> requestCubes => [60] Buffer size: 0
58300.8 <c-48#309:17> Sent requestCubes signal to root
58300.8 <c-48#309:17> Received 4 cubes from root
58300.8 <c-48#309:17> The main loop continues
58300.8 <c-48#309:17> Started solving a cube
58300.8 <c-48#309:17> Cube failed
58300.8 <c-48#309:17> Added failed cube
58300.8 <c-48#309:17> Started solving a cube
58577.1 <c-48#309:17> appl_pause was called
58577.1 <c-48#309:17> SUSPEND (0.00s since last cb)
58740.8 <c-48#309:17> appl_unpause was called
58740.8 <c-48#309:17> RESUME
58904.2 <c-48#309:17> appl_pause was called
58904.2 <c-48#309:17> SUSPEND (0.00s since last cb)
59063.4 <c-48#309:17> appl_unpause was called
59063.4 <c-48#309:17> RESUME
59260.5 <c-48#309:17> appl_interrupt was called
59260.5 <c-48#309:17> appl_interrupt was called
59260.5 <c-48#309:17> appl_withdraw was called
59260.5 <c-48#309:17> Started withdraw thread
59260.5 <c-48#309:17> STOP (0.00s since last cb)
59260.5 <c-48#309:17> Solving interrupted
59260.5 <c-48#309:17> The main loop continues
59260.5 <c-48#309:17> Leaving the main loop due to an interruption
59260.5 <c-48#309:17> Enter destructor of CubeWorker
59260.5 <c-48#309:17> Time waiting for messages: 0.000
59260.5 <c-48#309:17> Enter destructor of CubeWorkerInterface
59260.5 <c-48#309:17> Enter destructor of CubeRoot
59260.5 <c-48#309:17> Finished withdraw thread
59321.1 <c-48#309:17> Enter destructor
59321.1 <c-48#309:17> Time working: 197.086
59321.1 <c-48#309:17> Time suspended: 322.926
59321.1 <c-48#309:17> Joined cleanup thread
59321.1 <c-48#309:17> Exit destructor
59321.1 <c-48#309:17> Destructing logger
