129654 <c-19#391> Created logger
129654 <c-19#391> appl_initialize was called
129654 <c-19#391:5> Logger was updated
129654 <c-19#391:5> Started intializing cube lib
129654 <c-19#391:5> Finished intializing cube lib with worker, starting to work
129654 <c-19#391:5> requestCubes => [16] Buffer size: 0
129654 <c-19#391:5> Sent requestCubes signal to root
129654 <c-19#391:5> Received 1 cubes from root
129654 <c-19#391:5> The main loop continues
129654 <c-19#391:5> Started solving a cube
129654 <c-19#391:5> Cube failed
129654 <c-19#391:5> Added failed cube
129654 <c-19#391:5> returnFailedCubes => [16] Buffer size: 3
129654 <c-19#391:5> Sent 1 failed cubes to root
129654 <c-19#391:5> Received receivedFailedCubes signal from root
129654 <c-19#391:5> requestCubes => [16] Buffer size: 0
129654 <c-19#391:5> Sent requestCubes signal to root
129654 <c-19#391:5> Received 1 cubes from root
129654 <c-19#391:5> The main loop continues
129654 <c-19#391:5> Started solving a cube
129657 <c-19#391:5> appl_interrupt was called
129657 <c-19#391:5> Interrupting worker
129657 <c-19#391:5> appl_interrupt was called
129657 <c-19#391:5> appl_withdraw was called
129657 <c-19#391:5> Started withdraw thread
129657 <c-19#391:5> STOP (0.00s since last cb)
129657 <c-19#391:5> Solving interrupted
129657 <c-19#391:5> The main loop continues
129657 <c-19#391:5> Leaving the main loop due to an interruption
129657 <c-19#391:5> Finished withdrawing lib
129657 <c-19#391:5> Enter destructor of CubeWorker
129657 <c-19#391:5> Time waiting for messages: 0.000
129657 <c-19#391:5> Enter destructor of CubeWorkerInterface
129657 <c-19#391:5> Enter destructor of CubeRoot
129657 <c-19#391:5> Finished withdraw thread
129719 <c-19#391:5> Enter destructor
129719 <c-19#391:5> Time working: 2.867
129719 <c-19#391:5> Time suspended: 0.000
129719 <c-19#391:5> Joined cleanup thread
129719 <c-19#391:5> Exit destructor
129719 <c-19#391:5> Destructing logger
