17475.8 <c-36#103> Created logger
17475.8 <c-36#103> appl_initialize was called
17475.8 <c-36#103:4> Logger was updated
17475.8 <c-36#103:4> Started intializing cube lib
17475.8 <c-36#103:4> Finished intializing cube lib with worker, starting to work
17475.9 <c-36#103:4> requestCubes => [57] Buffer size: 0
17475.9 <c-36#103:4> Sent requestCubes signal to root
17475.9 <c-36#103:4> Received 1 cubes from root
17475.9 <c-36#103:4> The main loop continues
17475.9 <c-36#103:4> Started solving a cube
17476 <c-36#103:4> Cube failed
17476 <c-36#103:4> Added failed cube
17476 <c-36#103:4> returnFailedCubes => [57] Buffer size: 4
17476 <c-36#103:4> Sent 1 failed cubes to root
17476 <c-36#103:4> Received receivedFailedCubes signal from root
17476 <c-36#103:4> requestCubes => [57] Buffer size: 0
17476 <c-36#103:4> Sent requestCubes signal to root
17476 <c-36#103:4> Received 1 cubes from root
17476 <c-36#103:4> The main loop continues
17476 <c-36#103:4> Started solving a cube
18451.5 <c-36#103:4> appl_interrupt was called
18451.5 <c-36#103:4> Interrupting worker
18451.5 <c-36#103:4> appl_interrupt was called
18451.5 <c-36#103:4> appl_withdraw was called
18451.5 <c-36#103:4> Started withdraw thread
18451.6 <c-36#103:4> STOP (0.08s since last cb)
18451.6 <c-36#103:4> Solving interrupted
18451.6 <c-36#103:4> The main loop continues
18451.6 <c-36#103:4> Leaving the main loop due to an interruption
18451.6 <c-36#103:4> Finished withdrawing lib
18451.6 <c-36#103:4> Enter destructor of CubeWorker
18451.6 <c-36#103:4> Time waiting for messages: 0.000
18451.6 <c-36#103:4> Enter destructor of CubeWorkerInterface
18451.6 <c-36#103:4> Enter destructor of CubeRoot
18451.6 <c-36#103:4> Finished withdraw thread
18512.1 <c-36#103:4> Enter destructor
18512.1 <c-36#103:4> Time working: 975.775
18512.1 <c-36#103:4> Time suspended: 0.000
18512.1 <c-36#103:4> Joined cleanup thread
18512.1 <c-36#103:4> Exit destructor
18512.1 <c-36#103:4> Destructing logger
