79458.3 <c-6#237> Created logger
79458.3 <c-6#237> appl_initialize was called
79458.3 <c-6#237:26> Logger was updated
79458.3 <c-6#237:26> Started intializing cube lib
79458.3 <c-6#237:26> Finished intializing cube lib with worker, starting to work
79459 <c-6#237:26> requestCubes => [45] Buffer size: 0
79459 <c-6#237:26> Sent requestCubes signal to root
79459 <c-6#237:26> Received 1 cubes from root
79459 <c-6#237:26> The main loop continues
79459 <c-6#237:26> Started solving a cube
79537.1 <c-6#237:26> Cube failed
79537.1 <c-6#237:26> Added failed cube
79537.1 <c-6#237:26> returnFailedCubes => [45] Buffer size: 5
79537.1 <c-6#237:26> Sent 1 failed cubes to root
79537.1 <c-6#237:26> Received receivedFailedCubes signal from root
79537.1 <c-6#237:26> requestCubes => [45] Buffer size: 0
79537.1 <c-6#237:26> Sent requestCubes signal to root
79537.1 <c-6#237:26> Received 1 cubes from root
79537.1 <c-6#237:26> The main loop continues
79537.1 <c-6#237:26> Started solving a cube
80176.9 <c-6#237:26> appl_interrupt was called
80176.9 <c-6#237:26> Interrupting worker
80176.9 <c-6#237:26> appl_interrupt was called
80176.9 <c-6#237:26> appl_withdraw was called
80176.9 <c-6#237:26> STOP (0.02s since last cb)
80176.9 <c-6#237:26> Solving interrupted
80176.9 <c-6#237:26> The main loop continues
80176.9 <c-6#237:26> Leaving the main loop due to an interruption
80176.9 <c-6#237:26> Started withdraw thread
80176.9 <c-6#237:26> Finished withdrawing lib
80176.9 <c-6#237:26> Enter destructor of CubeWorker
80176.9 <c-6#237:26> Time waiting for messages: 0.000
80177.3 <c-6#237:26> Enter destructor of CubeWorkerInterface
80177.3 <c-6#237:26> Enter destructor of CubeRoot
80177.3 <c-6#237:26> Finished withdraw thread
80237.2 <c-6#237:26> Enter destructor
80237.2 <c-6#237:26> Time working: 718.602
80237.2 <c-6#237:26> Time suspended: 0.000
80237.2 <c-6#237:26> Joined cleanup thread
80237.2 <c-6#237:26> Exit destructor
80237.2 <c-6#237:26> Destructing logger
