49844.1 <c-37#150> Created logger
49844.3 <c-37#150> appl_initialize was called
49844.3 <c-37#150:50> Logger was updated
49844.3 <c-37#150:50> Started intializing cube lib
49844.3 <c-37#150:50> Finished intializing cube lib with worker, starting to work
49848.4 <c-37#150:50> requestCubes => [52] Buffer size: 0
49848.4 <c-37#150:50> Sent requestCubes signal to root
49848.4 <c-37#150:50> Received 1 cubes from root
49848.4 <c-37#150:50> The main loop continues
49848.4 <c-37#150:50> Started solving a cube
49920 <c-37#150:50> Cube failed
49920 <c-37#150:50> Added failed cube
49920.1 <c-37#150:50> returnFailedCubes => [52] Buffer size: 3
49920.1 <c-37#150:50> Sent 1 failed cubes to root
49920.1 <c-37#150:50> Received receivedFailedCubes signal from root
49920.1 <c-37#150:50> requestCubes => [52] Buffer size: 0
49920.1 <c-37#150:50> Sent requestCubes signal to root
49920.1 <c-37#150:50> Received 1 cubes from root
49920.1 <c-37#150:50> The main loop continues
49920.1 <c-37#150:50> Started solving a cube
50193.7 <c-37#150:50> appl_interrupt was called
50193.7 <c-37#150:50> Interrupting worker
50193.7 <c-37#150:50> appl_interrupt was called
50193.7 <c-37#150:50> appl_withdraw was called
50193.7 <c-37#150:50> STOP (0.09s since last cb)
50193.7 <c-37#150:50> Solving interrupted
50193.7 <c-37#150:50> The main loop continues
50193.7 <c-37#150:50> Leaving the main loop due to an interruption
50193.7 <c-37#150:50> Started withdraw thread
50193.7 <c-37#150:50> Finished withdrawing lib
50193.7 <c-37#150:50> Enter destructor of CubeWorker
50193.7 <c-37#150:50> Time waiting for messages: 0.000
50194.5 <c-37#150:50> Enter destructor of CubeWorkerInterface
50194.5 <c-37#150:50> Enter destructor of CubeRoot
50194.7 <c-37#150:50> Finished withdraw thread
50254.2 <c-37#150:50> Enter destructor
50254.2 <c-37#150:50> Time working: 349.348
50254.2 <c-37#150:50> Time suspended: 0.000
50254.2 <c-37#150:50> Joined cleanup thread
50254.2 <c-37#150:50> Exit destructor
50254.2 <c-37#150:50> Destructing logger
