14327 <c-36#42> Created logger
14327 <c-36#42> appl_initialize was called
14327 <c-36#42:9> Logger was updated
14327 <c-36#42:9> Started intializing cube lib
14327 <c-36#42:9> Finished intializing cube lib with worker, starting to work
14327.6 <c-36#42:9> requestCubes => [7] Buffer size: 0
14327.6 <c-36#42:9> Sent requestCubes signal to root
14327.6 <c-36#42:9> Received 1 cubes from root
14327.6 <c-36#42:9> The main loop continues
14327.6 <c-36#42:9> Started solving a cube
14334.3 <c-36#42:9> Cube failed
14334.3 <c-36#42:9> Added failed cube
14334.3 <c-36#42:9> returnFailedCubes => [7] Buffer size: 2
14334.3 <c-36#42:9> Sent 1 failed cubes to root
14334.3 <c-36#42:9> Received receivedFailedCubes signal from root
14334.3 <c-36#42:9> requestCubes => [7] Buffer size: 0
14334.3 <c-36#42:9> Sent requestCubes signal to root
14334.3 <c-36#42:9> Received 1 cubes from root
14334.3 <c-36#42:9> The main loop continues
14334.3 <c-36#42:9> Started solving a cube
14421.3 <c-36#42:9> appl_interrupt was called
14421.3 <c-36#42:9> Interrupting worker
14421.3 <c-36#42:9> appl_interrupt was called
14421.3 <c-36#42:9> appl_withdraw was called
14421.3 <c-36#42:9> STOP (0.00s since last cb)
14421.4 <c-36#42:9> Started withdraw thread
14421.4 <c-36#42:9> Solving interrupted
14421.4 <c-36#42:9> The main loop continues
14421.4 <c-36#42:9> Leaving the main loop due to an interruption
14421.4 <c-36#42:9> Finished withdrawing lib
14421.4 <c-36#42:9> Enter destructor of CubeWorker
14421.4 <c-36#42:9> Time waiting for messages: 0.001
14421.6 <c-36#42:9> Enter destructor of CubeWorkerInterface
14421.6 <c-36#42:9> Enter destructor of CubeRoot
14421.6 <c-36#42:9> Finished withdraw thread
14483.8 <c-36#42:9> Enter destructor
14483.8 <c-36#42:9> Time working: 94.335
14483.8 <c-36#42:9> Time suspended: 0.000
14483.8 <c-36#42:9> Joined cleanup thread
14483.8 <c-36#42:9> Exit destructor
14483.8 <c-36#42:9> Destructing logger
