56534 <c-36#167> Created logger
56534 <c-36#167> appl_initialize was called
56534 <c-36#167:11> Logger was updated
56534 <c-36#167:11> Started intializing cube lib
56534 <c-36#167:11> Finished intializing cube lib with worker, starting to work
56534.1 <c-36#167:11> requestCubes => [31] Buffer size: 0
56534.1 <c-36#167:11> Sent requestCubes signal to root
56534.1 <c-36#167:11> Received 1 cubes from root
56534.1 <c-36#167:11> The main loop continues
56534.1 <c-36#167:11> Started solving a cube
56550.2 <c-36#167:11> Cube failed
56550.2 <c-36#167:11> Added failed cube
56550.2 <c-36#167:11> returnFailedCubes => [31] Buffer size: 5
56550.2 <c-36#167:11> Sent 1 failed cubes to root
56550.2 <c-36#167:11> Received receivedFailedCubes signal from root
56550.2 <c-36#167:11> requestCubes => [31] Buffer size: 0
56550.2 <c-36#167:11> Sent requestCubes signal to root
56550.2 <c-36#167:11> Received 1 cubes from root
56550.2 <c-36#167:11> The main loop continues
56550.2 <c-36#167:11> Started solving a cube
57516.4 <c-36#167:11> appl_interrupt was called
57516.4 <c-36#167:11> Interrupting worker
57516.4 <c-36#167:11> appl_interrupt was called
57516.4 <c-36#167:11> appl_withdraw was called
57516.4 <c-36#167:11> Started withdraw thread
57516.4 <c-36#167:11> STOP (0.00s since last cb)
57516.4 <c-36#167:11> Solving interrupted
57516.4 <c-36#167:11> The main loop continues
57516.4 <c-36#167:11> Leaving the main loop due to an interruption
57516.4 <c-36#167:11> Finished withdrawing lib
57516.4 <c-36#167:11> Enter destructor of CubeWorker
57516.4 <c-36#167:11> Time waiting for messages: 0.000
57516.4 <c-36#167:11> Enter destructor of CubeWorkerInterface
57516.4 <c-36#167:11> Enter destructor of CubeRoot
57516.4 <c-36#167:11> Finished withdraw thread
57577.6 <c-36#167:11> Enter destructor
57577.6 <c-36#167:11> Time working: 982.324
57577.6 <c-36#167:11> Time suspended: 0.000
57577.6 <c-36#167:11> Joined cleanup thread
57577.6 <c-36#167:11> Exit destructor
57577.6 <c-36#167:11> Destructing logger
