60729.7 <c-23#348> Created logger
60729.7 <c-23#348> appl_initialize was called
60729.7 <c-23#348:2> Logger was updated
60729.7 <c-23#348:2> Started intializing cube lib
60729.7 <c-23#348:2> Finished intializing cube lib with worker, starting to work
60729.7 <c-23#348:2> requestCubes => [32] Buffer size: 0
60729.7 <c-23#348:2> Sent requestCubes signal to root
60729.7 <c-23#348:2> Received 1 cubes from root
60729.7 <c-23#348:2> The main loop continues
60729.7 <c-23#348:2> Started solving a cube
60729.7 <c-23#348:2> Cube failed
60729.7 <c-23#348:2> Added failed cube
60729.7 <c-23#348:2> returnFailedCubes => [32] Buffer size: 4
60729.7 <c-23#348:2> Sent 1 failed cubes to root
60729.7 <c-23#348:2> Received receivedFailedCubes signal from root
60729.7 <c-23#348:2> requestCubes => [32] Buffer size: 0
60729.7 <c-23#348:2> Sent requestCubes signal to root
60729.7 <c-23#348:2> Received 1 cubes from root
60729.7 <c-23#348:2> The main loop continues
60729.7 <c-23#348:2> Started solving a cube
60757.8 <c-23#348:2> appl_interrupt was called
60757.8 <c-23#348:2> Interrupting worker
60757.8 <c-23#348:2> STOP (0.00s since last cb)
60757.8 <c-23#348:2> appl_interrupt was called
60757.8 <c-23#348:2> appl_withdraw was called
60757.8 <c-23#348:2> Started withdraw thread
60757.8 <c-23#348:2> Solving interrupted
60757.8 <c-23#348:2> The main loop continues
60757.8 <c-23#348:2> Leaving the main loop due to an interruption
60757.8 <c-23#348:2> Finished withdrawing lib
60757.8 <c-23#348:2> Enter destructor of CubeWorker
60757.8 <c-23#348:2> Time waiting for messages: 0.000
60757.8 <c-23#348:2> Enter destructor of CubeWorkerInterface
60757.8 <c-23#348:2> Enter destructor of CubeRoot
60757.8 <c-23#348:2> Finished withdraw thread
60819.8 <c-23#348:2> Enter destructor
60819.8 <c-23#348:2> Time working: 28.117
60819.8 <c-23#348:2> Time suspended: 0.000
60819.8 <c-23#348:2> Joined cleanup thread
60819.8 <c-23#348:2> Exit destructor
60819.8 <c-23#348:2> Destructing logger
