4497.65 <c-31#28> Created logger
4497.67 <c-31#28> appl_initialize was called
4497.67 <c-31#28:3> Logger was updated
4497.67 <c-31#28:3> Started intializing cube lib
4497.67 <c-31#28:3> Finished intializing cube lib with worker, starting to work
4498.02 <c-31#28:3> requestCubes => [48] Buffer size: 0
4498.02 <c-31#28:3> Sent requestCubes signal to root
4498.02 <c-31#28:3> Received 1 cubes from root
4498.02 <c-31#28:3> The main loop continues
4498.02 <c-31#28:3> Started solving a cube
4498.02 <c-31#28:3> Cube failed
4498.02 <c-31#28:3> Added failed cube
4498.03 <c-31#28:3> returnFailedCubes => [48] Buffer size: 3
4498.03 <c-31#28:3> Sent 1 failed cubes to root
4498.03 <c-31#28:3> Received receivedFailedCubes signal from root
4498.04 <c-31#28:3> requestCubes => [48] Buffer size: 0
4498.04 <c-31#28:3> Sent requestCubes signal to root
4498.04 <c-31#28:3> Received 1 cubes from root
4498.04 <c-31#28:3> The main loop continues
4498.04 <c-31#28:3> Started solving a cube
5408.86 <c-31#28:3> appl_interrupt was called
5408.86 <c-31#28:3> Interrupting worker
5408.86 <c-31#28:3> STOP (0.00s since last cb)
5408.86 <c-31#28:3> appl_interrupt was called
5408.86 <c-31#28:3> appl_withdraw was called
5408.86 <c-31#28:3> Solving interrupted
5408.86 <c-31#28:3> The main loop continues
5408.86 <c-31#28:3> Leaving the main loop due to an interruption
5408.86 <c-31#28:3> Started withdraw thread
5408.86 <c-31#28:3> Finished withdrawing lib
5408.86 <c-31#28:3> Enter destructor of CubeWorker
5408.86 <c-31#28:3> Time waiting for messages: 0.001
5408.95 <c-31#28:3> Enter destructor of CubeWorkerInterface
5408.95 <c-31#28:3> Enter destructor of CubeRoot
5408.95 <c-31#28:3> Finished withdraw thread
5471.03 <c-31#28:3> Enter destructor
5471.03 <c-31#28:3> Time working: 911.191
5471.03 <c-31#28:3> Time suspended: 0.000
5471.03 <c-31#28:3> Joined cleanup thread
5471.03 <c-31#28:3> Exit destructor
5471.03 <c-31#28:3> Destructing logger
