32879.3 <c-0#190> Created logger
32879.7 <c-0#190> appl_initialize was called
32879.7 <c-0#190:1> Logger was updated
32879.7 <c-0#190:1> Started intializing cube lib
32879.7 <c-0#190:1> Finished intializing cube lib with worker, starting to work
32887.4 <c-0#190:1> requestCubes => [13] Buffer size: 0
32887.4 <c-0#190:1> Sent requestCubes signal to root
32887.4 <c-0#190:1> Received 1 cubes from root
32887.4 <c-0#190:1> The main loop continues
32887.4 <c-0#190:1> Started solving a cube
32887.4 <c-0#190:1> Cube failed
32887.4 <c-0#190:1> Added failed cube
32887.4 <c-0#190:1> returnFailedCubes => [13] Buffer size: 3
32887.4 <c-0#190:1> Sent 1 failed cubes to root
32887.4 <c-0#190:1> Received receivedFailedCubes signal from root
32887.4 <c-0#190:1> requestCubes => [13] Buffer size: 0
32887.4 <c-0#190:1> Sent requestCubes signal to root
32887.4 <c-0#190:1> Received 1 cubes from root
32887.4 <c-0#190:1> The main loop continues
32887.4 <c-0#190:1> Started solving a cube
33104.5 <c-0#190:1> appl_interrupt was called
33104.5 <c-0#190:1> Interrupting worker
33104.5 <c-0#190:1> appl_interrupt was called
33104.5 <c-0#190:1> appl_withdraw was called
33104.5 <c-0#190:1> Started withdraw thread
33128 <c-0#190:1> STOP (27.79s since last cb)
33131.2 <c-0#190:1> Solving interrupted
33131.2 <c-0#190:1> The main loop continues
33131.2 <c-0#190:1> Leaving the main loop due to an interruption
33131.2 <c-0#190:1> Finished withdrawing lib
33131.2 <c-0#190:1> Enter destructor of CubeWorker
33131.2 <c-0#190:1> Time waiting for messages: 0.000
33131.4 <c-0#190:1> Enter destructor of CubeWorkerInterface
33131.4 <c-0#190:1> Enter destructor of CubeRoot
33131.4 <c-0#190:1> Finished withdraw thread
33165.8 <c-0#190:1> Enter destructor
33165.8 <c-0#190:1> Time working: 224.785
33165.8 <c-0#190:1> Time suspended: 0.000
33165.8 <c-0#190:1> Joined cleanup thread
33165.8 <c-0#190:1> Exit destructor
33165.8 <c-0#190:1> Destructing logger
