13413.3 <c-8#73> Created logger
13413.3 <c-8#73:2> Logger was updated
13413.3 <c-8#73:2> Started intializing cube lib
13413.3 <c-8#73:2> Finished intializing cube lib with worker
13413.4 <c-8#73:2> requestCubes => [55] Buffer size: 0
13413.4 <c-8#73:2> Sent requestCubes signal to root
13413.4 <c-8#73:2> Received 4 cubes from root
13413.4 <c-8#73:2> The main loop continues
13413.4 <c-8#73:2> Started solving a cube
13413.5 <c-8#73:2> appl_pause was called
13413.5 <c-8#73:2> SUSPEND (0.00s since last cb)
13414.1 <c-8#73:2> appl_unpause was called
13414.1 <c-8#73:2> RESUME
13471 <c-8#73:2> Cube failed
13471 <c-8#73:2> Added failed cube
13471 <c-8#73:2> Started solving a cube
13887.6 <c-8#73:2> Cube failed
13887.6 <c-8#73:2> Added failed cube
13887.6 <c-8#73:2> Started solving a cube
13954 <c-8#73:2> Cube failed
13954 <c-8#73:2> Added failed cube
13954 <c-8#73:2> Started solving a cube
14317.4 <c-8#73:2> appl_interrupt was called
14317.4 <c-8#73:2> appl_interrupt was called
14317.4 <c-8#73:2> appl_withdraw was called
14317.4 <c-8#73:2> Started withdraw thread
14317.4 <c-8#73:2> STOP (0.03s since last cb)
14317.4 <c-8#73:2> Solving interrupted
14317.4 <c-8#73:2> The main loop continues
14317.4 <c-8#73:2> Leaving the main loop due to an interruption
14317.4 <c-8#73:2> Enter destructor of CubeWorker
14317.4 <c-8#73:2> Time waiting for messages: 0.001
14317.4 <c-8#73:2> Enter destructor of CubeWorkerInterface
14317.4 <c-8#73:2> Enter destructor of CubeRoot
14317.4 <c-8#73:2> Finished withdraw thread
14378.8 <c-8#73:2> Enter destructor
14378.8 <c-8#73:2> Time working: 903.303
14378.8 <c-8#73:2> Time suspended: 0.533
14378.8 <c-8#73:2> Joined cleanup thread
14378.8 <c-8#73:2> Exit destructor
14378.8 <c-8#73:2> Destructing logger
