18546.3 <c-22#112> Created logger
18546.3 <c-22#112> appl_initialize was called
18546.3 <c-22#112:5> Logger was updated
18546.3 <c-22#112:5> Started intializing cube lib
18546.3 <c-22#112:5> Finished intializing cube lib with worker, starting to work
18546.3 <c-22#112:5> requestCubes => [61] Buffer size: 0
18546.3 <c-22#112:5> Sent requestCubes signal to root
18546.3 <c-22#112:5> Received 1 cubes from root
18546.3 <c-22#112:5> The main loop continues
18546.3 <c-22#112:5> Started solving a cube
18579 <c-22#112:5> Cube failed
18579 <c-22#112:5> Added failed cube
18579 <c-22#112:5> returnFailedCubes => [61] Buffer size: 3
18579 <c-22#112:5> Sent 1 failed cubes to root
18579 <c-22#112:5> Received receivedFailedCubes signal from root
18579.1 <c-22#112:5> requestCubes => [61] Buffer size: 0
18579.1 <c-22#112:5> Sent requestCubes signal to root
18579.1 <c-22#112:5> Received 1 cubes from root
18579.1 <c-22#112:5> The main loop continues
18579.1 <c-22#112:5> Started solving a cube
19528.7 <c-22#112:5> appl_interrupt was called
19528.7 <c-22#112:5> Interrupting worker
19528.7 <c-22#112:5> STOP (0.00s since last cb)
19528.7 <c-22#112:5> Started withdraw thread
19528.7 <c-22#112:5> appl_interrupt was called
19528.7 <c-22#112:5> appl_withdraw was called
19528.7 <c-22#112:5> Solving interrupted
19528.7 <c-22#112:5> The main loop continues
19528.7 <c-22#112:5> Leaving the main loop due to an interruption
19528.7 <c-22#112:5> Finished withdrawing lib
19528.7 <c-22#112:5> Enter destructor of CubeWorker
19528.7 <c-22#112:5> Time waiting for messages: 0.000
19528.8 <c-22#112:5> Enter destructor of CubeWorkerInterface
19528.8 <c-22#112:5> Enter destructor of CubeRoot
19528.8 <c-22#112:5> Finished withdraw thread
19589.8 <c-22#112:5> Enter destructor
19589.8 <c-22#112:5> Time working: 982.447
19589.8 <c-22#112:5> Time suspended: 0.000
19589.8 <c-22#112:5> Joined cleanup thread
19589.8 <c-22#112:5> Exit destructor
19589.8 <c-22#112:5> Destructing logger
